services:
  backend_troian:
    image: vitaliktroian04/smart-energy-stability:latest
    ports:
      - "8085:8085"
    restart: always    

  pokazovaSlurzba:
    image: bondarenkorodion/slurzba1
    ports:
      - "3000:3000"